// portraits.js
// Profile portrait avatars. Extracted from the removed loot module on the
// social-only branch: these are profile pictures, not game rewards.

const PROFILE_PORTRAITS = [
  // ─── Human Men ───
  { id: 'hm_knight', name: 'Knight', icon: '\u{1F6E1}\uFE0F', img: '/icons/characters/hm_knight.png' },
  { id: 'hm_knight2', name: 'Knight Captain', icon: '\u2694\uFE0F', img: '/icons/characters/hm_knight2.png' },
  { id: 'hm_knight3', name: 'Noble Knight', icon: '\u{1F6E1}\uFE0F', img: '/icons/characters/hm_knight3.png' },
  { id: 'hm_warrior', name: 'Warrior', icon: '\u2694\uFE0F', img: '/icons/characters/hm_warrior.png' },
  { id: 'hm_bold', name: 'Bold Warrior', icon: '\u2694\uFE0F', img: '/icons/characters/hm_bold.png' },
  { id: 'hm_viking', name: 'Viking', icon: '\u{1FA93}', img: '/icons/characters/hm_viking.png' },
  { id: 'hm_jarl', name: 'Jarl', icon: '\u{1F451}', img: '/icons/characters/hm_jarl.png' },
  { id: 'hm_samurai', name: 'Samurai', icon: '\u2694\uFE0F', img: '/icons/characters/hm_samurai.png' },
  { id: 'hm_ronin', name: 'Ronin', icon: '\u2694\uFE0F', img: '/icons/characters/hm_ronin.png' },
  { id: 'hm_archer', name: 'Archer', icon: '\u{1F3F9}', img: '/icons/characters/hm_archer.png' },
  { id: 'hm_barbarian', name: 'Barbarian', icon: '\u{1FA93}', img: '/icons/characters/hm_barbarian.png' },
  { id: 'hm_templar', name: 'Templar', icon: '\u{1F6E1}\uFE0F', img: '/icons/characters/hm_templar.png' },
  { id: 'hm_alchemist', name: 'Alchemist', icon: '\u{1F9D9}', img: '/icons/characters/hm_alchemist.png' },
  { id: 'hm_rogue', name: 'Rogue', icon: '\u{1F977}', img: '/icons/characters/hm_rogue.png' },
  { id: 'hm_priest', name: 'Priest', icon: '\u{1F9DD}', img: '/icons/characters/hm_priest.png' },
  { id: 'hm_lord', name: 'Lord', icon: '\u{1F451}', img: '/icons/characters/hm_lord.png' },
  { id: 'hm_darklord', name: 'Dark Lord', icon: '\u{1F47F}', img: '/icons/characters/hm_darklord.png' },
  { id: 'hm_captain', name: 'Captain', icon: '\u{1F6E1}\uFE0F', img: '/icons/characters/hm_captain.png' },
  { id: 'hm_scout', name: 'Scout', icon: '\u{1F3F9}', img: '/icons/characters/hm_scout.png' },
  { id: 'hm_shinobi', name: 'Shinobi', icon: '\u{1F977}', img: '/icons/characters/hm_shinobi.png' },
  { id: 'hm_sage', name: 'Sage', icon: '\u{1F9D9}', img: '/icons/characters/hm_sage.png' },
  { id: 'hm_pharaoh', name: 'Pharaoh', icon: '\u{1F451}', img: '/icons/characters/hm_pharaoh.png' },
  { id: 'hm_conquistador', name: 'Conquistador', icon: '\u2694\uFE0F', img: '/icons/characters/hm_conquistador.png' },
  { id: 'hm_thug', name: 'Thug', icon: '\u{1F977}', img: '/icons/characters/hm_thug.png' },
  { id: 'hm_chief', name: 'Chief', icon: '\u{1F451}', img: '/icons/characters/hm_chief.png' },
  // ─── Human Women ───
  { id: 'hw_princess', name: 'Princess', icon: '\u{1F451}', img: '/icons/characters/hw_princess.png' },
  { id: 'hw_queen', name: 'Queen', icon: '\u{1F451}', img: '/icons/characters/hw_queen.png' },
  { id: 'hw_amazon', name: 'Amazon Warrior', icon: '\u2694\uFE0F', img: '/icons/characters/hw_amazon.png' },
  { id: 'hw_knight', name: 'Woman Knight', icon: '\u{1F6E1}\uFE0F', img: '/icons/characters/hw_knight.png' },
  { id: 'hw_archer', name: 'Archer', icon: '\u{1F3F9}', img: '/icons/characters/hw_archer.png' },
  { id: 'hw_warrior', name: 'Woman Warrior', icon: '\u2694\uFE0F', img: '/icons/characters/hw_warrior.png' },
  { id: 'hw_witch1', name: 'Witch', icon: '\u{1F9D9}', img: '/icons/characters/hw_witch1.png' },
  { id: 'hw_witch2', name: 'Dark Witch', icon: '\u{1F9D9}', img: '/icons/characters/hw_witch2.png' },
  { id: 'hw_shaman', name: 'Shaman', icon: '\u{1F9D9}', img: '/icons/characters/hw_shaman.png' },
  { id: 'hw_viking', name: 'Viking Woman', icon: '\u{1FA93}', img: '/icons/characters/hw_viking.png' },
  { id: 'hw_noble1', name: 'Noble Lady', icon: '\u{1F451}', img: '/icons/characters/hw_noble1.png' },
  { id: 'hw_noble2', name: 'Noblewoman', icon: '\u{1F451}', img: '/icons/characters/hw_noble2.png' },
  { id: 'hw_maiden', name: 'Maiden', icon: '\u{1F9DD}', img: '/icons/characters/hw_maiden.png' },
  { id: 'hw_queen2', name: 'Golden Queen', icon: '\u{1F451}', img: '/icons/characters/hw_queen2.png' },
  { id: 'hw_girl', name: 'Young Girl', icon: '\u{1F9DD}', img: '/icons/characters/hw_girl.png' },
  // ─── Elves ───
  { id: 'elf_warrior', name: 'Elf Warrior', icon: '\u{1F9DD}', img: '/icons/characters/elf_warrior.png' },
  { id: 'elf_m1', name: 'Elf Ranger', icon: '\u{1F3F9}', img: '/icons/characters/elf_m1.png' },
  { id: 'elf_m2', name: 'Elf Lord', icon: '\u{1F451}', img: '/icons/characters/elf_m2.png' },
  { id: 'elf_m3', name: 'Elf Scout', icon: '\u{1F3F9}', img: '/icons/characters/elf_m3.png' },
  { id: 'elf_m4', name: 'Elf Sage', icon: '\u{1F9D9}', img: '/icons/characters/elf_m4.png' },
  { id: 'elf_m5', name: 'Elf Prince', icon: '\u{1F451}', img: '/icons/characters/elf_m5.png' },
  { id: 'elf_mage', name: 'Elf Mage', icon: '\u{1F9D9}', img: '/icons/characters/elf_mage.png' },
  { id: 'elf_f1', name: 'Elf Maiden', icon: '\u{1F9DD}', img: '/icons/characters/elf_f1.png' },
  { id: 'elf_f2', name: 'Elf Priestess', icon: '\u{1F9DD}', img: '/icons/characters/elf_f2.png' },
  { id: 'elf_f3', name: 'Elf Enchantress', icon: '\u{1F9D9}', img: '/icons/characters/elf_f3.png' },
  { id: 'elf_hunter', name: 'Elf Hunter', icon: '\u{1F3F9}', img: '/icons/characters/elf_hunter.png' },
  { id: 'elf_f5', name: 'Elf Mystic', icon: '\u{1F9D9}', img: '/icons/characters/elf_f5.png' },
  { id: 'elf_f6', name: 'Elf Guardian', icon: '\u{1F6E1}\uFE0F', img: '/icons/characters/elf_f6.png' },
  // ─── Gnomes ───
  { id: 'gnome_f1', name: 'Gnome Tinkerer', icon: '\u{1F9DD}', img: '/icons/characters/gnome_f1.png' },
  { id: 'gnome_f2', name: 'Gnome Alchemist', icon: '\u{1F9D9}', img: '/icons/characters/gnome_f2.png' },
  { id: 'gnome_f3', name: 'Gnome Witch', icon: '\u{1F9D9}', img: '/icons/characters/gnome_f3.png' },
  { id: 'gnome_dark', name: 'Dark Gnome', icon: '\u{1F47F}', img: '/icons/characters/gnome_dark.png' },
  { id: 'gnome_m1', name: 'Gnome Engineer', icon: '\u{1F9DD}', img: '/icons/characters/gnome_m1.png' },
  { id: 'gnome_m2', name: 'Gnome Sage', icon: '\u{1F9D9}', img: '/icons/characters/gnome_m2.png' },
  { id: 'gnome_m3', name: 'Gnome Elder', icon: '\u{1F9D9}', img: '/icons/characters/gnome_m3.png' },
];

module.exports = { PROFILE_PORTRAITS };
